name: pedidos_papajohns
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/actual.jpeg
   - assets/pasado.jpeg
   - assets/papajohns.png

  fonts:
   - family: FrancoisOne
     fonts:
       - asset: fonts/FrancoisOne-Regular.ttf
