name: papa_johns_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/1.png
   - assets/2.png
   - assets/3.png
   - assets/4.png
   - assets/5.png
   - assets/6.png
   - assets/7.png
   - assets/8.png
   - assets/9.png
   - assets/10.png
   - assets/11.png
   - assets/12.png
   - assets/13.png
   - assets/14.png
   - assets/15.png
   - assets/16.png
   - assets/17.png
   - assets/18.png
   - assets/19.png
   - assets/20.png
   - assets/21.png
   - assets/22.png
   - assets/23.png
   - assets/24.png
   - assets/25.png
   - assets/26.png
   - assets/27.png
   - assets/28.png
   - assets/29.png
   - assets/30.png
   - assets/31.png
   - assets/32.png
   - assets/33.png
   - assets/34.png
   - assets/35.png
   - assets/36.png
   - assets/37.png
   - assets/38.png
   - assets/39.png
   - assets/40.png
   - assets/41.png
   - assets/42.png
   - assets/43.png
   - assets/44.png
   - assets/45.png
   - assets/46.png
   - assets/47.png
   - assets/48.png
   - assets/49.png
   - assets/50.png
   - assets/51.png
   - assets/52.png
   - assets/53.png
   - assets/arma.png
   - assets/mitad.png
   - assets/papajohns.png
   - assets/actual.jpeg
   - assets/pasado.jpeg
   - assets/perfil.jpeg
  
  fonts:
   - family: FrancoisOne
     fonts:
       - asset: fonts/FrancoisOne-Regular.ttf
