name: appsmovil2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/cumpleanos.png
   - assets/digital.png
   - assets/familia.png
   - assets/fena.png
   - assets/mama.png
   - assets/may.png
   - assets/santorcuato.jpeg
   - assets/whats.png


splashsscreen: ^1.3.0
